### ISSUE TITLE
Readme examples use public override for protected functions

### ISSUE THREAD

**Issue by dror-g** [toastisme/OpenGOAP#2]
Seems the Readme HarvestWood example uses some `public override` to access protected methods,
For example - in Action - `OnActivateDerived`, or in Goal - `SetupDerived`.

Everything seems to work fine if I just set these to `protected override` on my Action/Goal scripts, so might just be a matter of updating the readme.

Thanks for this great tool!

**Comment by toastisme** [comment]
Thanks for pointing this out. The change to using `*Derived` protected methods was a last minute thing to ensure the corresponding base methods are always called. I'll add an explicit example in the near future to avoid the example being out of sync.

I've updated the Readme so closing this. Glad you're getting some use out of it!
