### ISSUE TITLE
worldState.AddTemporaryState does not exist?

### ISSUE THREAD

**Issue by dror-g** [toastisme/OpenGOAP#3]
Can't seem to use worldState.AddTemporaryState.
I see it in GOAPAction.cs but can't call it from Action.

No a must for me, It's just that it appears in README example.

**Comment by dror-g** [comment]
Correction - as it's in GOAPActions, it can be called inside an action with `AddTemporaryState()`.
So I guess just need to correct the readme line `worldState.AddTemporaryState` ...

**Comment by toastisme** [comment]
Thanks for spotting that! Corrected the README.
